CREATE TABLE "certifications" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(50) NOT NULL,
	"name" varchar(100) NOT NULL,
	"standard_code" varchar(100),
	"certificate_number" varchar(100),
	"full_name_hu" text NOT NULL,
	"full_name_en" text NOT NULL,
	"full_name_de" text NOT NULL,
	"full_name_zh" text NOT NULL,
	"description_hu" text,
	"description_en" text,
	"description_de" text,
	"description_zh" text,
	"scope_hu" text,
	"scope_en" text,
	"scope_de" text,
	"scope_zh" text,
	"issuer" text NOT NULL,
	"issuer_url" text,
	"accreditation_body" varchar(50),
	"accreditation_number" varchar(50),
	"iaf_mla_member" boolean DEFAULT false NOT NULL,
	"verify_url" text,
	"issued_date" date,
	"expires_date" date,
	"credential_category" text,
	"logo_url" text,
	"pdf_url" text,
	"active" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "certifications_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE INDEX "idx_certifications_active_sort" ON "certifications" USING btree ("active","sort_order") WHERE "certifications"."active" = true;