CREATE TABLE "site_settings" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"legal_name" text NOT NULL,
	"legal_name_short" text NOT NULL,
	"alternate_name" text NOT NULL,
	"registration_id" text NOT NULL,
	"tax_id" text NOT NULL,
	"vat_id" text NOT NULL,
	"address_street" text NOT NULL,
	"address_postal_code" varchar(20) NOT NULL,
	"address_locality" text NOT NULL,
	"address_country" varchar(2) DEFAULT 'HU' NOT NULL,
	"address_short" text NOT NULL,
	"maps_url" text NOT NULL,
	"phone" text NOT NULL,
	"phone_display" text NOT NULL,
	"phone_tel" text NOT NULL,
	"email" text NOT NULL,
	"email_href" text NOT NULL,
	"office_hours_hu" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "site_settings_singleton_id" CHECK ("site_settings"."id" = 1)
);
